behaviors:
  ExploreAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      activation: tanh

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    max_steps: 2.0e6
    time_horizon: 64
    summary_freq: 10000

    keep_checkpoints: 5
    checkpoint_interval: 500000

environment_parameters:
  difficulty:
    curriculum:
      - name: Level 1
        completion_criteria:
          measure: reward
          behavior: ExploreAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 0.4
        value: 1.0

      - name: Level 2
        completion_criteria:
          measure: reward
          behavior: ExploreAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 0.7
        value: 2.0

      - name: Level 3
        completion_criteria:
          measure: reward
          behavior: ExploreAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 0.9
        value: 3.0

